In [46]:
import Bio
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio import SeqIO
from Bio import Align
from Bio import SeqIO
from Bio.Align import substitution_matrices

import pandas as pd

In [47]:
##Make a function to define sequences from a fasta file.

def define_seq(pathway, form, reference_name, new_name):
    for seq in SeqIO.parse(pathway, form):
        if seq.name == reference_name:
            new_name = seq.seq
            return new_name

In [48]:
##Define S.cerevisiae ERG11 sequence and C.Albicans as well

ScERG11 = define_seq(r"c:S288C_YHR007C_ERG11_protein.fsa","fasta","ERG11", "ScERG11" )
print(ScERG11)

CaERG11 = define_seq(r"c:CaERG11.fsa","fasta","ERG11", "CaERG11" )
print(CaERG11)

MSATKSIVGEALEYVNIGLSHFLALPLAQRISLIIIIPFIYNIVWQLLYSLRKDRPPLVFYWIPWVGSAVVYGMKPYEFFEECQKKYGDIFSFVLLGRVMTVYLGPKGHEFVFNAKLADVSAEAAYAHLTTPVFGKGVIYDCPNSRLMEQKKFVKGALTKEAFKSYVPLIAEEVYKYFRDSKNFRLNERTTGTIDVMVTQPEMTIFTASRSLLGKEMRAKLDTDFAYLYSDLDKGFTPINFVFPNLPLEHYRKRDHAQKAISGTYMSLIKERRKNNDIQDRDLIDSLMKNSTYKDGVKMTDQEIANLLIGVLMGGQHTSAATSAWILLHLAERPDVQQELYEEQMRVLDGGKKELTYDLLQEMPLLNQTIKETLRMHHPLHSLFRKVMKDMHVPNTSYVIPAGYHVLVSPGYTHLRDEYFPNAHQFNIHRWNKDSASSYSVGEEVDYGFGAISKGVSSPYLPFGGGRHRCIGEHFAYCQLGVLMSIFIRTLKWHYPEGKTVPPPDFTSMVTLPTGPAKIIWEKRNPEQKI*
MAIVETVIDGINYFLSLSVTQQISILLGVPFVYNLVWQYLYSLRKDRAPLVFYWIPWFGSAASYGQQPYEFFESCRQKYGDVFSFMLLGKIMTVYLGPKGHEFVFNAKLSDVSAEDAYKHLTTPVFGKGVIYDCPNSRLMEQKKFAKFALTTDSFKRYVPKIREEILNYFVTDESFKLKEKTHGVANVMKTQPEITIFTASRSLFGDEMRRIFDRSFAQLYSDLDKGFTPINFVFPNLPLPHYWRRDAAQKKISATYMKEIKSRRERGDIDPNRDLIDSLLIHSTYKDGVKMTDQEIANLLIGILMGGQHTSASTSAWFLLHLGEKPHLQDVIYQEVVELLKEKGGDLNDLTYEDLQKLPSVNNTIKETLRMHMPLHSIFRKVTNPLRIPETNYIVPKGHYVLVSPGYAHTSERYFDNPEDFDPTRWDTAAAKANSVSFNSSDEVDYGFGKVSKGVSSPYLPFGGGRHRCIGEQFAYVQLGTILTTFVYNLRWTIDGYKVPDPDYSSMVVLPTEPAEIIWEKRETCMF*

In [49]:
##Prepare the alignments parameters and make the alignment

aligner = Align.PairwiseAligner()
aligner.open_gap_score = -10
aligner.extend_gap_score = -0.5
aligner.substitution_matrix = substitution_matrices.load("BLOSUM62")

alignments = aligner.align(ScERG11, CaERG11)
print(alignments[0])

MSATKSIVGEALEYVNIGLSHFLALPLAQRISLIIIIPFIYNIVWQLLYSLRKDRPPLVFYWIPWVGSAVVYGMKPYEFFEECQKKYGDIFSFVLLGRVMTVYLGPKGHEFVFNAKLADVSAEAAYAHLTTPVFGKGVIYDCPNSRLMEQKKFVKGALTKEAFKSYVPLIAEEVYKYFRDSKNFRLNERTTGTIDVMVTQPEMTIFTASRSLLGKEMRAKLDTDFAYLYSDLDKGFTPINFVFPNLPLEHYRKRDHAQKAISGTYMSLIKERRKNNDIQ-DRDLIDSLMKNSTYKDGVKMTDQEIANLLIGVLMGGQHTSAATSAWILLHLAERPDVQQELYEEQMRVL---DGGKKELTYDLLQEMPLLNQTIKETLRMHHPLHSLFRKVMKDMHVPNTSYVIPAGYHVLVSPGYTHLRDEYFPNAHQFNIHRWN----KDSASSYSVGEEVDYGFGAISKGVSSPYLPFGGGRHRCIGEHFAYCQLGVLMSIFIRTLKWHYPEGKTVPPPDFTSMVTLPTGPAKIIWEKRNPEQKI*
|........--------|...||.|...|.||.....||.||.|||.||||||||.|||||||||.|||..||..||||||.|..||||.|||.|||..||||||||||||||||||.|||||.||.||||||||||||||||||||||||||.|.|||...||.|||.|.||...||.....|.|.|.|.|...||.||||.|||||||||.|.|||...|..||.|||||||||||||||||||||.||..||.|||.||.|||..||.||...||.-.|||||||...||||||||||||||||||||.|||||||||.||||.||||.|.|..|...|.|....|---.|....|||..||..|..|.|||||||||.||||.||||......|.|.|..|.|..|||||||.|....||.|...|...||.----|....|.....|||||||..|||||||||||||||||||||.|||.|||.....|...|.|..-.|..||.||..|||.|||.||.||||||.-....|
MAIVETVID--------GINYFLSLSVTQQISILLGVPFVYNLVWQYLYSLRKDRAPLVFYWIPWFGSAASYGQQPYEFFESCRQKYGDVFSFMLLGKIMTVYLGPKGHEFVFNAKLSDVSAEDAYKHLTTPVFGKGVIYDCPNSRLMEQKKFAKFALTTDSFKRYVPKIREEILNYFVTDESFKLKEKTHGVANVMKTQPEITIFTASRSLFGDEMRRIFDRSFAQLYSDLDKGFTPINFVFPNLPLPHYWRRDAAQKKISATYMKEIKSRRERGDIDPNRDLIDSLLIHSTYKDGVKMTDQEIANLLIGILMGGQHTSASTSAWFLLHLGEKPHLQDVIYQEVVELLKEKGGDLNDLTYEDLQKLPSVNNTIKETLRMHMPLHSIFRKVTNPLRIPETNYIVPKGHYVLVSPGYAHTSERYFDNPEDFDPTRWDTAAAKANSVSFNSSDEVDYGFGKVSKGVSSPYLPFGGGRHRCIGEQFAYVQLGTILTTFVYNLRWTI-DGYKVPDPDYSSMVVLPTEPAEIIWEKRE-TCMF*

In [57]:
##Alignment function

def align_seq(target,query):
    aligner = Align.PairwiseAligner()
    aligner.open_gap_score = -10
    aligner.extend_gap_score = -0.5
    aligner.substitution_matrix = substitution_matrices.load("BLOSUM62")
    score = aligner.score(target, query)
    print(score)
    alignments = aligner.align(target,query)
    print(alignments[0]) 
    return alignments[0]

Sc_Ca_Align = align_seq(ScERG11,CaERG11)

1797.0
MSATKSIVGEALEYVNIGLSHFLALPLAQRISLIIIIPFIYNIVWQLLYSLRKDRPPLVFYWIPWVGSAVVYGMKPYEFFEECQKKYGDIFSFVLLGRVMTVYLGPKGHEFVFNAKLADVSAEAAYAHLTTPVFGKGVIYDCPNSRLMEQKKFVKGALTKEAFKSYVPLIAEEVYKYFRDSKNFRLNERTTGTIDVMVTQPEMTIFTASRSLLGKEMRAKLDTDFAYLYSDLDKGFTPINFVFPNLPLEHYRKRDHAQKAISGTYMSLIKERRKNNDIQ-DRDLIDSLMKNSTYKDGVKMTDQEIANLLIGVLMGGQHTSAATSAWILLHLAERPDVQQELYEEQMRVL---DGGKKELTYDLLQEMPLLNQTIKETLRMHHPLHSLFRKVMKDMHVPNTSYVIPAGYHVLVSPGYTHLRDEYFPNAHQFNIHRWN----KDSASSYSVGEEVDYGFGAISKGVSSPYLPFGGGRHRCIGEHFAYCQLGVLMSIFIRTLKWHYPEGKTVPPPDFTSMVTLPTGPAKIIWEKRNPEQKI*
|........--------|...||.|...|.||.....||.||.|||.||||||||.|||||||||.|||..||..||||||.|..||||.|||.|||..||||||||||||||||||.|||||.||.||||||||||||||||||||||||||.|.|||...||.|||.|.||...||.....|.|.|.|.|...||.||||.|||||||||.|.|||...|..||.|||||||||||||||||||||.||..||.|||.||.|||..||.||...||.-.|||||||...||||||||||||||||||||.|||||||||.||||.||||.|.|..|...|.|....|---.|....|||..||..|..|.|||||||||.||||.||||......|.|.|..|.|..|||||||.|....||.|...|...||.----|....|.....|||||||..|||||||||||||||||||||.|||.|||.....|...|.|..-.|..||.||..|||.|||.||.||||||.-....|
MAIVETVID--------GINYFLSLSVTQQISILLGVPFVYNLVWQYLYSLRKDRAPLVFYWIPWFGSAASYGQQPYEFFESCRQKYGDVFSFMLLGKIMTVYLGPKGHEFVFNAKLSDVSAEDAYKHLTTPVFGKGVIYDCPNSRLMEQKKFAKFALTTDSFKRYVPKIREEILNYFVTDESFKLKEKTHGVANVMKTQPEITIFTASRSLFGDEMRRIFDRSFAQLYSDLDKGFTPINFVFPNLPLPHYWRRDAAQKKISATYMKEIKSRRERGDIDPNRDLIDSLLIHSTYKDGVKMTDQEIANLLIGILMGGQHTSASTSAWFLLHLGEKPHLQDVIYQEVVELLKEKGGDLNDLTYEDLQKLPSVNNTIKETLRMHMPLHSIFRKVTNPLRIPETNYIVPKGHYVLVSPGYAHTSERYFDNPEDFDPTRWDTAAAKANSVSFNSSDEVDYGFGKVSKGVSSPYLPFGGGRHRCIGEQFAYVQLGTILTTFVYNLRWTI-DGYKVPDPDYSSMVVLPTEPAEIIWEKRE-TCMF*

In [87]:
##Split the alignment to be able to use the aligned sequences
Sc_Ca_Align_str = str(align_seq(ScERG11,CaERG11))
Sc_Ca_Align_split = Sc_Ca_Align_str.split("\n")
print(Sc_Ca_Align_split)

1797.0
MSATKSIVGEALEYVNIGLSHFLALPLAQRISLIIIIPFIYNIVWQLLYSLRKDRPPLVFYWIPWVGSAVVYGMKPYEFFEECQKKYGDIFSFVLLGRVMTVYLGPKGHEFVFNAKLADVSAEAAYAHLTTPVFGKGVIYDCPNSRLMEQKKFVKGALTKEAFKSYVPLIAEEVYKYFRDSKNFRLNERTTGTIDVMVTQPEMTIFTASRSLLGKEMRAKLDTDFAYLYSDLDKGFTPINFVFPNLPLEHYRKRDHAQKAISGTYMSLIKERRKNNDIQ-DRDLIDSLMKNSTYKDGVKMTDQEIANLLIGVLMGGQHTSAATSAWILLHLAERPDVQQELYEEQMRVL---DGGKKELTYDLLQEMPLLNQTIKETLRMHHPLHSLFRKVMKDMHVPNTSYVIPAGYHVLVSPGYTHLRDEYFPNAHQFNIHRWN----KDSASSYSVGEEVDYGFGAISKGVSSPYLPFGGGRHRCIGEHFAYCQLGVLMSIFIRTLKWHYPEGKTVPPPDFTSMVTLPTGPAKIIWEKRNPEQKI*
|........--------|...||.|...|.||.....||.||.|||.||||||||.|||||||||.|||..||..||||||.|..||||.|||.|||..||||||||||||||||||.|||||.||.||||||||||||||||||||||||||.|.|||...||.|||.|.||...||.....|.|.|.|.|...||.||||.|||||||||.|.|||...|..||.|||||||||||||||||||||.||..||.|||.||.|||..||.||...||.-.|||||||...||||||||||||||||||||.|||||||||.||||.||||.|.|..|...|.|....|---.|....|||..||..|..|.|||||||||.||||.||||......|.|.|..|.|..|||||||.|....||.|...|...||.----|....|.....|||||||..|||||||||||||||||||||.|||.|||.....|...|.|..-.|..||.||..|||.|||.||.||||||.-....|
MAIVETVID--------GINYFLSLSVTQQISILLGVPFVYNLVWQYLYSLRKDRAPLVFYWIPWFGSAASYGQQPYEFFESCRQKYGDVFSFMLLGKIMTVYLGPKGHEFVFNAKLSDVSAEDAYKHLTTPVFGKGVIYDCPNSRLMEQKKFAKFALTTDSFKRYVPKIREEILNYFVTDESFKLKEKTHGVANVMKTQPEITIFTASRSLFGDEMRRIFDRSFAQLYSDLDKGFTPINFVFPNLPLPHYWRRDAAQKKISATYMKEIKSRRERGDIDPNRDLIDSLLIHSTYKDGVKMTDQEIANLLIGILMGGQHTSASTSAWFLLHLGEKPHLQDVIYQEVVELLKEKGGDLNDLTYEDLQKLPSVNNTIKETLRMHMPLHSIFRKVTNPLRIPETNYIVPKGHYVLVSPGYAHTSERYFDNPEDFDPTRWDTAAAKANSVSFNSSDEVDYGFGKVSKGVSSPYLPFGGGRHRCIGEQFAYVQLGTILTTFVYNLRWTI-DGYKVPDPDYSSMVVLPTEPAEIIWEKRE-TCMF*

['MSATKSIVGEALEYVNIGLSHFLALPLAQRISLIIIIPFIYNIVWQLLYSLRKDRPPLVFYWIPWVGSAVVYGMKPYEFFEECQKKYGDIFSFVLLGRVMTVYLGPKGHEFVFNAKLADVSAEAAYAHLTTPVFGKGVIYDCPNSRLMEQKKFVKGALTKEAFKSYVPLIAEEVYKYFRDSKNFRLNERTTGTIDVMVTQPEMTIFTASRSLLGKEMRAKLDTDFAYLYSDLDKGFTPINFVFPNLPLEHYRKRDHAQKAISGTYMSLIKERRKNNDIQ-DRDLIDSLMKNSTYKDGVKMTDQEIANLLIGVLMGGQHTSAATSAWILLHLAERPDVQQELYEEQMRVL---DGGKKELTYDLLQEMPLLNQTIKETLRMHHPLHSLFRKVMKDMHVPNTSYVIPAGYHVLVSPGYTHLRDEYFPNAHQFNIHRWN----KDSASSYSVGEEVDYGFGAISKGVSSPYLPFGGGRHRCIGEHFAYCQLGVLMSIFIRTLKWHYPEGKTVPPPDFTSMVTLPTGPAKIIWEKRNPEQKI*', '|........--------|...||.|...|.||.....||.||.|||.||||||||.|||||||||.|||..||..||||||.|..||||.|||.|||..||||||||||||||||||.|||||.||.||||||||||||||||||||||||||.|.|||...||.|||.|.||...||.....|.|.|.|.|...||.||||.|||||||||.|.|||...|..||.|||||||||||||||||||||.||..||.|||.||.|||..||.||...||.-.|||||||...||||||||||||||||||||.|||||||||.||||.||||.|.|..|...|.|....|---.|....|||..||..|..|.|||||||||.||||.||||......|.|.|..|.|..|||||||.|....||.|...|...||.----|....|.....|||||||..|||||||||||||||||||||.|||.|||.....|...|.|..-.|..||.||..|||.|||.||.||||||.-....|', 'MAIVETVID--------GINYFLSLSVTQQISILLGVPFVYNLVWQYLYSLRKDRAPLVFYWIPWFGSAASYGQQPYEFFESCRQKYGDVFSFMLLGKIMTVYLGPKGHEFVFNAKLSDVSAEDAYKHLTTPVFGKGVIYDCPNSRLMEQKKFAKFALTTDSFKRYVPKIREEILNYFVTDESFKLKEKTHGVANVMKTQPEITIFTASRSLFGDEMRRIFDRSFAQLYSDLDKGFTPINFVFPNLPLPHYWRRDAAQKKISATYMKEIKSRRERGDIDPNRDLIDSLLIHSTYKDGVKMTDQEIANLLIGILMGGQHTSASTSAWFLLHLGEKPHLQDVIYQEVVELLKEKGGDLNDLTYEDLQKLPSVNNTIKETLRMHMPLHSIFRKVTNPLRIPETNYIVPKGHYVLVSPGYAHTSERYFDNPEDFDPTRWDTAAAKANSVSFNSSDEVDYGFGKVSKGVSSPYLPFGGGRHRCIGEQFAYVQLGTILTTFVYNLRWTI-DGYKVPDPDYSSMVVLPTEPAEIIWEKRE-TCMF*', '']

In [93]:
##Obtain the align position and aa in the target according to a query position.
#We have to count the number of ---- added in the sequences to have the good aa and position
#Because python count from 0, you have to remove 1 from the position

def compare_aa_align(alignment, position):
    position = position -1
    new_align = str(alignment)
    new_align_split = new_align.split("\n")
    query_align = new_align_split[0]
    target_align = new_align_split[2]
    target_tiret_count = target_align[0:position + 1].count("-")
    print(target_tiret_count)
    target_aa_position = position - target_tiret_count
    print(target_aa_position +1)
    print(target_align[target_aa_position])
    query_tiret_count = query_align[0:position + 1].count("-")
    query_aa_position = position - query_tiret_count
    print(query_aa_position + 1)
    print(query_align[query_aa_position])
        
compare_aa_align(Sc_Ca_Align,63)

8
55
R
63
I

In [85]:
##Import a position list from the query sequence

pos_file = pd.read_excel(r"C:query_position.xlsx",sheet_name=0, header=None)
pos_file

       0
0     63
1     65
2     66
3     67
4     68
..   ...
201  508
202  509
203  510
204  511
205  512

[206 rows x 1 columns]

In [168]:
pos_list = list(pos_file[0])

In [169]:
##From that, we can make a function that takes a list of query positions and 
#return it for the target.

def compare_pos_list(alignment, pos_list):
    
    targetposlist = []
    queryposlist = []
    targetAAlist = []
    queryAAlist = []
    
    for position in pos_list:
        position = position -1
        new_align = str(alignment)
        new_align_split = new_align.split("\n")
        query_align = new_align_split[0]
        target_align = new_align_split[2]
        
        target_tiret_count = target_align[0:position + 1].count("-")

        query_tiret_count = query_align[0:position + 1].count("-")
        query_aa_position = position + query_tiret_count  
 
        target_position = position - target_tiret_count + query_tiret_count
        
        targetposlist.append(target_position+1)
        queryposlist.append(position +1)
        targetAAlist.append(target_align[query_aa_position])
        queryAAlist.append(query_align[query_aa_position])
    
    dictionary = {'query_pos': queryposlist, 'query_aa': queryAAlist, 'target_pos': targetposlist, 'target_aa': targetAAlist}  
    dataframe = pd.DataFrame(dictionary) 
    dataframe.to_csv('compare_pos_list.csv')
    
    return dataframe

In [177]:
Ca_SC_analysis = compare_pos_list(Sc_Ca_Align, pos_list)
Ca_SC_analysis.to_csv('pos_list.csv')

In [175]:
####Make a big function that takes all of that (except the sequences)
##align+compare

def find_aligned_positions(query, target, pos_list):
        
    aligner = Align.PairwiseAligner()
    aligner.open_gap_score = -10
    aligner.extend_gap_score = -0.5
    aligner.substitution_matrix = substitution_matrices.load("BLOSUM62")

    alignments = aligner.align(query, target)
    alignment = alignments[0]
    
    targetposlist = []
    queryposlist = []
    targetAAlist = []
    queryAAlist = []
    
    for position in pos_list:
        position = position -1
        new_align = str(alignment)
        new_align_split = new_align.split("\n")
        query_align = new_align_split[0]
        target_align = new_align_split[2]
        
        target_tiret_count = target_align[0:position + 1].count("-")

        query_tiret_count = query_align[0:position + 1].count("-")
        query_aa_position = position + query_tiret_count  
 
        target_position = position - target_tiret_count + query_tiret_count
        
        targetposlist.append(target_position+1)
        queryposlist.append(position +1)
        targetAAlist.append(target_align[query_aa_position])
        queryAAlist.append(query_align[query_aa_position])
    
    dictionary = {'query_pos': queryposlist, 'query_aa': queryAAlist, 'target_pos': targetposlist, 'target_aa': targetAAlist}  
    dataframe = pd.DataFrame(dictionary) 
    dataframe.to_csv('compare_pos_list.csv')
    
    return dataframe

In [178]:
Ca_SC_analysis = find_aligned_positions(ScERG11,CaERG11, pos_list)
Ca_SC_analysis.to_csv('pos_list2.csv')
Ca_SC_analysis

     query_pos query_aa  target_pos target_aa
0           63        I          55         I
1           65        W          57         W
2           66        V          58         F
3           67        G          59         G
4           68        S          60         S
..         ...      ...         ...       ...
201        508        S         507         S
202        509        M         508         M
203        510        V         509         V
204        511        T         510         V
205        512        L         511         L

[206 rows x 4 columns]